"""Kiralama modeline kdv_orani eklendi

Revision ID: 00b74606dfe8
Revises: 67498d03d7fa
Create Date: 2025-11-11 05:20:15.523140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b74606dfe8'
down_revision = '67498d03d7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kdv_orani', sa.Integer(), nullable=False,server_default='20'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.drop_column('kdv_orani')

    # ### end Alembic commands ###
