""" nakliye

Revision ID: 0d63e5c80c96
Revises: 3496446bf810
Create Date: 2025-12-23 01:11:25.952737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d63e5c80c96'
down_revision = '3496446bf810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hizmet_kaydi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ozel_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hizmet_kaydi', schema=None) as batch_op:
        batch_op.drop_column('ozel_id')

    # ### end Alembic commands ###
