"""firma imza yetkisi alanlari

Revision ID: 26eabe885604
Revises: f4b5be4fa0e6
Create Date: 2026-02-02 23:33:19.818052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26eabe885604'
down_revision = 'f4b5be4fa0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imza_yetkisi_kontrol_edildi', sa.Boolean(), nullable=False,server_default=sa.false()))
        batch_op.add_column(sa.Column('imza_yetkisi_kontrol_tarihi', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('imza_yetkisi_kontrol_eden_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imza_arsiv_notu', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_column('imza_arsiv_notu')
        batch_op.drop_column('imza_yetkisi_kontrol_eden_id')
        batch_op.drop_column('imza_yetkisi_kontrol_tarihi')
        batch_op.drop_column('imza_yetkisi_kontrol_edildi')

    # ### end Alembic commands ###
