""" nakliye

Revision ID: 3496446bf810
Revises: cca1561d3743
Create Date: 2025-12-22 19:45:01.327060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3496446bf810'
down_revision = 'cca1561d3743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hizmet_kaydi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nakliye_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_hizmet_kaydi_nakliye_id', 'nakliye', ['nakliye_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hizmet_kaydi', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hizmet_kaydi_nakliye_id', type_='foreignkey')
        batch_op.drop_column('nakliye_id')

    # ### end Alembic commands ###
