"""empty message

Revision ID: 7dff002f208a
Revises: 26eabe885604
Create Date: 2026-02-11 22:41:48.627060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dff002f208a'
down_revision = '26eabe885604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('eposta', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_firma_eposta'), ['eposta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firma_eposta'))
        batch_op.drop_column('eposta')
        batch_op.drop_column('telefon')

    # ### end Alembic commands ###
