"""yenileme

Revision ID: 9a8ed0be6794
Revises: 
Create Date: 2026-02-12 23:50:50.015685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8ed0be6794'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_adi', sa.String(length=150), nullable=False),
    sa.Column('yetkili_adi', sa.String(length=100), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('eposta', sa.String(length=120), nullable=True),
    sa.Column('iletisim_bilgileri', sa.Text(), nullable=False),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=False),
    sa.Column('vergi_no', sa.String(length=50), nullable=False),
    sa.Column('is_musteri', sa.Boolean(), nullable=False),
    sa.Column('is_tedarikci', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bakiye', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('imza_yetkisi_kontrol_edildi', sa.Boolean(), nullable=False),
    sa.Column('imza_yetkisi_kontrol_tarihi', sa.DateTime(), nullable=True),
    sa.Column('imza_yetkisi_kontrol_eden_id', sa.Integer(), nullable=True),
    sa.Column('imza_arsiv_notu', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firma_eposta'), ['eposta'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_firma_adi'), ['firma_adi'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_is_musteri'), ['is_musteri'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_is_tedarikci'), ['is_tedarikci'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_vergi_no'), ['vergi_no'], unique=True)

    op.create_table('kasa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kasa_adi', sa.String(length=100), nullable=False),
    sa.Column('tipi', sa.String(length=20), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bakiye', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ekipman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=100), nullable=False),
    sa.Column('yakit', sa.String(length=50), nullable=False),
    sa.Column('tipi', sa.String(length=100), nullable=False),
    sa.Column('marka', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('seri_no', sa.String(length=100), nullable=False),
    sa.Column('calisma_yuksekligi', sa.Integer(), nullable=False),
    sa.Column('kaldirma_kapasitesi', sa.Integer(), nullable=False),
    sa.Column('uretim_tarihi', sa.String(length=100), nullable=False),
    sa.Column('calisma_durumu', sa.String(length=50), nullable=False),
    sa.Column('giris_maliyeti', sa.String(length=50), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('firma_tedarikci_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_tedarikci_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma_tedarikci_id', 'seri_no', name='_tedarikci_seri_no_uc')
    )
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ekipman_kod'), ['kod'], unique=True)
        batch_op.create_index(batch_op.f('ix_ekipman_seri_no'), ['seri_no'], unique=False)

    op.create_table('kiralama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiralama_form_no', sa.String(length=100), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=False),
    sa.Column('doviz_kuru_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('doviz_kuru_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('firma_musteri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firma_musteri_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nakliye',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('guzergah', sa.String(length=200), nullable=False),
    sa.Column('plaka', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cari_islendi_mi', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nakliye', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nakliye_cari_islendi_mi'), ['cari_islendi_mi'], unique=False)

    op.create_table('odeme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_musteri_id', sa.Integer(), nullable=False),
    sa.Column('kasa_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('yon', sa.String(length=20), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['firma_musteri_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['kasa_id'], ['kasa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stok_karti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parca_kodu', sa.String(length=100), nullable=False),
    sa.Column('parca_adi', sa.String(length=250), nullable=False),
    sa.Column('mevcut_stok', sa.Integer(), nullable=False),
    sa.Column('varsayilan_tedarikci_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['varsayilan_tedarikci_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stok_karti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stok_karti_parca_kodu'), ['parca_kodu'], unique=True)

    op.create_table('bakim_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ekipman_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.String(length=50), nullable=False),
    sa.Column('aciklama', sa.String(length=500), nullable=True),
    sa.Column('calisma_saati', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hizmet_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('nakliye_id', sa.Integer(), nullable=True),
    sa.Column('ozel_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.Column('yon', sa.String(length=10), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['nakliye_id'], ['nakliye.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiralama_kalemi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiralama_id', sa.Integer(), nullable=False),
    sa.Column('ekipman_id', sa.Integer(), nullable=True),
    sa.Column('is_dis_tedarik_ekipman', sa.Boolean(), nullable=True),
    sa.Column('harici_ekipman_tipi', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_marka', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_model', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_seri_no', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_kapasite', sa.Integer(), nullable=True),
    sa.Column('harici_ekipman_yukseklik', sa.Integer(), nullable=True),
    sa.Column('harici_ekipman_uretim_yili', sa.Integer(), nullable=True),
    sa.Column('harici_ekipman_tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('kiralama_baslangici', sa.Date(), nullable=False),
    sa.Column('kiralama_bitis', sa.Date(), nullable=False),
    sa.Column('kiralama_brm_fiyat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kiralama_alis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_oz_mal_nakliye', sa.Boolean(), nullable=True),
    sa.Column('is_harici_nakliye', sa.Boolean(), nullable=True),
    sa.Column('nakliye_satis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nakliye_alis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nakliye_tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('nakliye_araci_id', sa.Integer(), nullable=True),
    sa.Column('sonlandirildi', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], ),
    sa.ForeignKeyConstraint(['harici_ekipman_tedarikci_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['kiralama_id'], ['kiralama.id'], ),
    sa.ForeignKeyConstraint(['nakliye_araci_id'], ['ekipman.id'], ),
    sa.ForeignKeyConstraint(['nakliye_tedarikci_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stok_hareket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stok_karti_id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.String(length=50), nullable=False),
    sa.Column('adet', sa.Integer(), nullable=False),
    sa.Column('birim_fiyat', sa.String(length=50), nullable=True),
    sa.Column('hareket_tipi', sa.String(length=20), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['stok_karti_id'], ['stok_karti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kullanilan_parca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bakim_kaydi_id', sa.Integer(), nullable=False),
    sa.Column('stok_karti_id', sa.Integer(), nullable=False),
    sa.Column('kullanilan_adet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bakim_kaydi_id'], ['bakim_kaydi.id'], ),
    sa.ForeignKeyConstraint(['stok_karti_id'], ['stok_karti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('makine_degisimleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('eski_ekipman_id', sa.Integer(), nullable=False),
    sa.Column('yeni_ekipman_id', sa.Integer(), nullable=False),
    sa.Column('kiralama_kalemi_id', sa.Integer(), nullable=False),
    sa.Column('degisim_nedeni', sa.String(length=100), nullable=False),
    sa.Column('eski_ekipman_saati', sa.Integer(), nullable=True),
    sa.Column('yeni_ekipman_saati', sa.Integer(), nullable=True),
    sa.Column('nakliye_ucreti', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eski_ekipman_id'], ['ekipman.id'], ),
    sa.ForeignKeyConstraint(['kiralama_kalemi_id'], ['kiralama_kalemi.id'], ),
    sa.ForeignKeyConstraint(['yeni_ekipman_id'], ['ekipman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('makine_degisimleri')
    op.drop_table('kullanilan_parca')
    op.drop_table('stok_hareket')
    op.drop_table('kiralama_kalemi')
    op.drop_table('hizmet_kaydi')
    op.drop_table('bakim_kaydi')
    with op.batch_alter_table('stok_karti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stok_karti_parca_kodu'))

    op.drop_table('stok_karti')
    op.drop_table('odeme')
    with op.batch_alter_table('nakliye', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nakliye_cari_islendi_mi'))

    op.drop_table('nakliye')
    op.drop_table('kiralama')
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ekipman_seri_no'))
        batch_op.drop_index(batch_op.f('ix_ekipman_kod'))

    op.drop_table('ekipman')
    op.drop_table('kasa')
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firma_vergi_no'))
        batch_op.drop_index(batch_op.f('ix_firma_is_tedarikci'))
        batch_op.drop_index(batch_op.f('ix_firma_is_musteri'))
        batch_op.drop_index(batch_op.f('ix_firma_firma_adi'))
        batch_op.drop_index(batch_op.f('ix_firma_eposta'))

    op.drop_table('firma')
    # ### end Alembic commands ###
