"""Firma modeline sözleşme ve bulut alanları eklendi

Revision ID: a4ced6192411
Revises: 9a8ed0be6794
Create Date: 2026-02-15 21:43:44.022114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ced6192411'
down_revision = '9a8ed0be6794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_firma')
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sozlesme_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sozlesme_rev_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sozlesme_tarihi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('bulut_klasor_adi', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_firma_bulut_klasor_adi'), ['bulut_klasor_adi'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_firma_bulut_klasor_adi'), type_='unique')
        batch_op.drop_column('bulut_klasor_adi')
        batch_op.drop_column('sozlesme_tarihi')
        batch_op.drop_column('sozlesme_rev_no')
        batch_op.drop_column('sozlesme_no')

    op.create_table('_alembic_tmp_firma',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firma_adi', sa.VARCHAR(length=150), nullable=False),
    sa.Column('yetkili_adi', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telefon', sa.VARCHAR(length=20), nullable=True),
    sa.Column('eposta', sa.VARCHAR(length=120), nullable=True),
    sa.Column('iletisim_bilgileri', sa.TEXT(), nullable=False),
    sa.Column('vergi_dairesi', sa.VARCHAR(length=100), nullable=False),
    sa.Column('vergi_no', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_musteri', sa.BOOLEAN(), nullable=False),
    sa.Column('is_tedarikci', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('bakiye', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('imza_yetkisi_kontrol_edildi', sa.BOOLEAN(), nullable=False),
    sa.Column('imza_yetkisi_kontrol_tarihi', sa.DATETIME(), nullable=True),
    sa.Column('imza_yetkisi_kontrol_eden_id', sa.INTEGER(), nullable=True),
    sa.Column('imza_arsiv_notu', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sozlesme_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sozlesme_rev_no', sa.INTEGER(), nullable=False),
    sa.Column('sozlesme_tarihi', sa.DATE(), nullable=True),
    sa.Column('bulut_klasor_adi', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulut_klasor_adi', name=op.f('uq_firma_bulut_klasor_adi'))
    )
    # ### end Alembic commands ###
