""" kasa aktiif eklendi

Revision ID: f4b5be4fa0e6
Revises: 0d63e5c80c96
Create Date: 2026-02-01 23:04:19.562632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b5be4fa0e6'
down_revision = '0d63e5c80c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
